"""Server-side measurement, scraped from SGLang's Prometheus endpoint.

Client-side timing includes everything between our `send()` and our parse of
the first chunk: network, kernel buffers, event-loop wakeup, and our own SSE
parsing. On loopback with a lightly loaded client that overhead is ~1ms and can
be ignored. It cannot be ignored when the client is saturated, or remote, or
when the load is generated by agents on a laptop.

The server's own histograms measure from request arrival to first token, inside
the inference system. That makes the number independent of where load is
generated — which is what lets an agent-driven track on a different machine
produce numbers comparable to the deterministic in-container suite.

Reporting both is the point: their *difference* is the client-plus-network
overhead, so the harness can prove its own measurements are clean rather than
assuming it.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

# Histogram buckets are cumulative counters, so a "snapshot" is only meaningful
# as a difference between two points in time.
_LINE = re.compile(r'^(?P<name>[a-zA-Z_:][\w:]*)(?P<labels>\{[^}]*\})?\s+(?P<value>\S+)$')
_LE = re.compile(r'le="([^"]+)"')

INTERESTING = (
    "sglang:time_to_first_token_seconds",
    "sglang:inter_token_latency_seconds",
    "sglang:e2e_request_latency_seconds",
    "sglang:queue_time_seconds",
    "sglang:cache_hit_rate",
    "sglang:num_queue_reqs",
    "sglang:num_running_reqs",
    "sglang:gen_throughput",
    # Actual GPU compute time, as opposed to wall clock. Cost attribution must
    # use this: a level held for 90s with an idle GPU consumes 90 wall-seconds
    # but very little compute, and charging the idle time to the few tokens
    # processed makes them look enormously expensive.
    # Real GPU time per forward pass, labelled by phase. Requires
    # SGLANG_ENABLE_METRICS_DEVICE_TIMER=1 in the server env (see
    # modal_app._server_env); without it the counter is never incremented.
    "sglang:forward_execution_seconds_total",
    "sglang:dp_cooperation_forward_execution_seconds_total",
    "sglang:estimated_flops_per_gpu_total",
    "sglang:estimated_read_bytes_per_gpu_total",
    "sglang:prompt_tokens_total",
    "sglang:generation_tokens_total",
    "sglang:cached_tokens_total",
    "sglang:num_requests_total",
)


@dataclass
class Snapshot:
    """One scrape: histogram buckets, counters and gauges."""
    buckets: dict[str, dict[float, float]]
    counters: dict[str, float]
    gauges: dict[str, float]

    @staticmethod
    def parse(text: str) -> "Snapshot":
        buckets: dict[str, dict[float, float]] = {}
        counters: dict[str, float] = {}
        gauges: dict[str, float] = {}
        for raw in text.splitlines():
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            m = _LINE.match(line)
            if not m:
                continue
            name, labels, val = m["name"], m["labels"] or "", m["value"]
            try:
                v = float(val)
            except ValueError:
                continue
            if name.endswith("_bucket"):
                le = _LE.search(labels)
                if le:
                    base = name[: -len("_bucket")]
                    edge = float("inf") if le.group(1) in ("+Inf", "Inf") else float(le.group(1))
                    buckets.setdefault(base, {})[edge] = \
                        buckets.setdefault(base, {}).get(edge, 0.0) + v
            elif name.endswith(("_sum", "_count", "_total")):
                counters[name] = counters.get(name, 0.0) + v
            else:
                gauges[name] = v
        return Snapshot(buckets, counters, gauges)


def _quantile_from_buckets(delta: dict[float, float], q: float) -> float | None:
    """Interpolate a quantile from cumulative histogram buckets.

    Resolution is limited by bucket width, so this is coarser than an exact
    percentile over per-request samples. It is authoritative about *where* the
    time was spent, which the client cannot see at all.
    """
    if not delta:
        return None
    edges = sorted(delta)
    total = max(delta[e] for e in edges)
    if total <= 0:
        return None
    target = q * total
    prev_edge, prev_count = 0.0, 0.0
    for e in edges:
        c = delta[e]
        if c >= target:
            if e == float("inf"):
                return prev_edge
            span = c - prev_count
            frac = (target - prev_count) / span if span > 0 else 0.0
            return prev_edge + (e - prev_edge) * frac
        prev_edge, prev_count = (e if e != float("inf") else prev_edge), c
    return prev_edge


def diff(before: Snapshot, after: Snapshot) -> dict:
    """Per-workload view: what happened between two scrapes."""
    out: dict = {}

    for base in set(after.buckets) | set(before.buckets):
        if not any(base.startswith(i) for i in INTERESTING):
            continue
        a, b = after.buckets.get(base, {}), before.buckets.get(base, {})
        d = {e: a.get(e, 0.0) - b.get(e, 0.0) for e in set(a) | set(b)}
        n = max(d.values()) if d else 0
        if n <= 0:
            continue
        out[base] = {
            "n": round(n),
            "p50": _quantile_from_buckets(d, 0.50),
            "p95": _quantile_from_buckets(d, 0.95),
            "p99": _quantile_from_buckets(d, 0.99),
        }
        s = f"{base}_sum"
        if s in after.counters and s in before.counters and n:
            out[base]["mean"] = (after.counters[s] - before.counters[s]) / n

    for k in set(after.counters) | set(before.counters):
        if not any(k.startswith(i) for i in INTERESTING):
            continue
        d = after.counters.get(k, 0.0) - before.counters.get(k, 0.0)
        if d:
            out.setdefault("counters", {})[k] = d

    for k, v in after.gauges.items():
        if any(k.startswith(i) for i in INTERESTING):
            out.setdefault("gauges_final", {})[k] = v
    return out


async def scrape(base_url: str, timeout_s: float = 10.0) -> Snapshot | None:
    import aiohttp
    try:
        async with aiohttp.ClientSession() as s:
            async with s.get(base_url.rstrip("/") + "/metrics",
                             timeout=aiohttp.ClientTimeout(total=timeout_s)) as r:
                if r.status != 200:
                    return None
                return Snapshot.parse(await r.text())
    except Exception:
        return None


def compare_client_server(client_ttft_ms: dict, server: dict) -> dict:
    """How much of measured TTFT was the client and the network?

    A large gap means the client is contributing to the number we are calling
    server latency, and the run should be treated as suspect.
    """
    st = server.get("sglang:time_to_first_token_seconds")
    if not st or st.get("p50") is None:
        return {"available": False}
    s50 = st["p50"] * 1000
    c50 = client_ttft_ms.get("p50")
    if c50 is None:
        return {"available": False}
    return {
        "available": True,
        "client_p50_ms": round(c50, 1),
        "server_p50_ms": round(s50, 1),
        "overhead_ms": round(c50 - s50, 1),
        "overhead_pct": round((c50 - s50) / c50 * 100, 1) if c50 else None,
        "note": ("client-side TTFT minus server-side TTFT is network plus client "
                 "overhead; on loopback with an unsaturated client it should be "
                 "a few ms. Large or growing means the client is polluting the "
                 "measurement."),
    }


class BatchSampler:
    """Sample `num_running_reqs` during a measured window.

    Needed because the cost attribution's output coefficient came out ~10x
    worse than the memory-bandwidth roofline at the decode mix's nominal batch
    of 32 -- and exactly on roofline at a batch of 3. Before/after gauge
    scrapes cannot tell those apart: they catch the queue at two instants, not
    what the scheduler actually ran.

    Deliberately light. Polling `nvidia-smi` four times a second from inside
    the container starved the load generator and moved N* from 128 to 32 -- the
    instrument changed the measurement, worst at high load. This is one HTTP
    GET against a local endpoint every couple of seconds, which is orders of
    magnitude cheaper, but keep the interval coarse regardless.
    """

    def __init__(self, base_url: str, interval_s: float = 2.0):
        self.base_url = base_url
        self.interval_s = interval_s
        self.running: list[float] = []
        self.queued: list[float] = []
        self._task = None
        self._stop = None

    async def _loop(self) -> None:
        import asyncio
        while not self._stop.is_set():
            snap = await scrape(self.base_url, timeout_s=3.0)
            if snap:
                r = snap.gauges.get("sglang:num_running_reqs")
                q = snap.gauges.get("sglang:num_queue_reqs")
                if r is not None:
                    self.running.append(r)
                if q is not None:
                    self.queued.append(q)
            try:
                await asyncio.wait_for(self._stop.wait(), self.interval_s)
            except asyncio.TimeoutError:
                pass

    async def __aenter__(self) -> "BatchSampler":
        import asyncio
        self._stop = asyncio.Event()
        self._task = asyncio.create_task(self._loop())
        return self

    async def __aexit__(self, *exc) -> None:
        import contextlib
        self._stop.set()
        if self._task is not None:
            with contextlib.suppress(Exception):
                await self._task

    def summary(self, warmup_frac: float = 0.0) -> dict:
        """Mean running batch is the number the cost model needs.

        `warmup_frac` drops the leading fraction of samples. Without it the
        mean includes the ramp from an empty scheduler, while `summarize()`
        already excludes warmup from goodput -- so the two describe different
        windows and Little's Law (batch = throughput * time-in-server) fails
        for a reason that is pure bookkeeping. The bias grows with load,
        because a larger batch takes longer to fill.
        """
        def stat(xs: list[float]) -> dict:
            if warmup_frac > 0 and len(xs) > 4:
                xs = xs[int(len(xs) * warmup_frac):]
            if not xs:
                return {"n": 0}
            s = sorted(xs)
            return {"n": len(xs), "mean": round(sum(xs) / len(xs), 2),
                    "p50": s[len(s) // 2], "max": s[-1],
                    "frac_idle": round(sum(1 for x in xs if x == 0) / len(xs), 3)}
        return {"running": stat(self.running), "queued": stat(self.queued)}
