"""Generate docs/capacity.md from the roofline model.

Run after any change to model, hardware, or the workload mix:

    uv run python scripts/capacity_report.py

Generated rather than hand-written so the numbers cannot drift from the code
that sizes the load suite.
"""
from __future__ import annotations

import pathlib

from autoinf.flops import (H100, H100_8X, QWEN3_30B_A3B, QWEN3_235B_A22B,
                           capacity, request_cost)
from autoinf.prompts import CATEGORIES

OUT = pathlib.Path(__file__).resolve().parents[1] / "docs" / "capacity.md"

# Measured on 1xH100, 2026-08-29 (see docs/HANDOFF.md).
MEASURED_MAX_RPS = 34.3
MEASURED_KNEE_LO, MEASURED_KNEE_HI = 35.6, 49.1
MEASURED_TPOT_MS = 24.0


def _mix_profile() -> tuple[int, int]:
    """Weighted mean input/output tokens for the realistic human mix."""
    import math
    tw = sum(c.weight for c in CATEGORIES)
    mi = sum(c.weight * math.exp(c.in_mu + c.in_sigma ** 2 / 2) for c in CATEGORIES) / tw
    mo = sum(c.weight * math.exp(c.out_mu + c.out_sigma ** 2 / 2) for c in CATEGORIES) / tw
    return int(mi), int(mo)


def main() -> None:
    m, hw = QWEN3_30B_A3B, H100
    in_tok, out_tok = 537, 233          # the `sustained` profile we measured
    c = capacity(m, hw, in_tok, out_tok, batch=146)
    mix_in, mix_out = _mix_profile()
    cmix = capacity(m, hw, mix_in, mix_out, batch=146)
    big = capacity(QWEN3_235B_A22B, H100_8X, in_tok, out_tok, batch=256)

    L = []
    w = L.append
    w("# Capacity model\n")
    w("Generated by `scripts/capacity_report.py`. Do not edit by hand.\n")
    w("Every number here is a **ceiling**, not a forecast. Real serving lands well")
    w("under it — attention traffic, KV reads, imperfect overlap, and prefill")
    w("stealing decode steps all cost throughput. The useful output is the *ratio*:")
    w("hitting 60% of the roofline is a healthy server, 5% means something is wrong.\n")

    w("## Why two rooflines\n")
    w("Prefill and decode sit on opposite sides of the roofline:\n")
    w("- **Prefill is compute-bound.** A long prompt is one big matmul; the limit is FLOP/s.")
    w("- **Decode is memory-bound.** Each step reads weights to emit one token per")
    w("  sequence; the limit is HBM bandwidth.\n")
    w("For an MoE this second point is sharper than it first appears. Routing is")
    w("per-token, so at any real batch size the tokens in one step collectively")
    w("reach nearly *every* expert. `active_params` predicts FLOPs correctly and")
    w("under-predicts **bytes** badly.\n")

    w(f"    experts touched at batch  32: {m.experts_touched(32):.0f} / {m.n_experts}")
    w(f"    experts touched at batch  64: {m.experts_touched(64):.0f} / {m.n_experts}")
    w(f"    experts touched at batch 128: {m.experts_touched(128):.0f} / {m.n_experts}\n")
    w("So a decode step reads close to the whole model, not 10% of it.\n")

    w("## Model\n")
    w(f"`{m.name}`\n")
    w("| | |")
    w("|---|---|")
    w(f"| total parameters | {m.total_params/1e9:.1f}B |")
    w(f"| active parameters / token | {m.active_params/1e9:.2f}B |")
    w(f"| layers | {m.n_layers} |")
    w(f"| attention | {m.n_heads} Q heads, {m.n_kv_heads} KV heads (GQA), head dim {m.head_dim} |")
    w(f"| experts | {m.n_experts} total, {m.n_experts_active} active per token |")
    w(f"| dense FLOPs / token | {m.dense_flops_per_token()/1e9:.2f} GFLOP |")
    w(f"| KV cache / token | {m.kv_bytes_per_token()/1024:.1f} KiB |")
    w("")

    w("## Hardware\n")
    w(f"`{hw.name}`: {hw.peak_flops_dense/1e12:.0f} TFLOP/s dense FP8, ")
    w(f"{hw.hbm_bandwidth/1e12:.2f} TB/s HBM3, {hw.hbm_bytes/1e9:.0f} GB.\n")
    w("Peak FLOPs is the **dense** figure. The commonly quoted ~1979 TFLOP/s")
    w("assumes 2:4 structured sparsity, which inference serving does not use.\n")

    w(f"## Ceiling for the measured profile ({in_tok} in / {out_tok} out)\n")
    w("| | |")
    w("|---|---|")
    w(f"| FLOPs per request | {c['per_request_tflops']:.2f} TFLOP "
      f"({c['prefill_tflops']:.2f} prefill + {c['decode_tflops']:.2f} decode) |")
    w(f"| decode step reads | {c['decode_bytes_per_step_gb']:.1f} GB |")
    w(f"| decode step time | {c['decode_step_ms']:.2f} ms |")
    w(f"| bound by | **{c['bound_by']}** |")
    w(f"| roofline max | **{c['max_rps_roofline']:.1f} rps** |")
    w(f"| roofline output tokens | {c['max_output_tok_s_roofline']:.0f} tok/s |")
    w("")

    w("### Validation against measurement\n")
    w("| | |")
    w("|---|---|")
    w(f"| roofline ceiling | {c['max_rps_roofline']:.1f} rps |")
    w(f"| **measured** max throughput | **{MEASURED_MAX_RPS} rps** |")
    w(f"| achieved fraction | **{MEASURED_MAX_RPS/c['max_rps_roofline']:.0%}** |")
    w(f"| measured SLO knee | {MEASURED_KNEE_LO}–{MEASURED_KNEE_HI} rps |")
    w(f"| theoretical decode step | {c['decode_step_ms']:.2f} ms |")
    w(f"| **measured** p99 TPOT | {MEASURED_TPOT_MS:.1f} ms |")
    w("")
    w(f"{MEASURED_MAX_RPS/c['max_rps_roofline']:.0%} of the bandwidth roofline is a")
    w("healthy result for a real serving stack. The gap between the theoretical")
    w(f"{c['decode_step_ms']:.1f} ms decode step and the measured {MEASURED_TPOT_MS:.0f} ms TPOT")
    w("is the clearest single lead we have: it is roughly the cost of prefill")
    w("chunks interleaving into decode batches, which is exactly what a scheduler")
    w("change can move.\n")

    w(f"## Ceiling for the human mix ({mix_in} in / {mix_out} out)\n")
    w("Weighted over the request categories in `prompts.py`.\n")
    w("| | |")
    w("|---|---|")
    w(f"| FLOPs per request | {cmix['per_request_tflops']:.2f} TFLOP |")
    w(f"| bound by | {cmix['bound_by']} |")
    w(f"| roofline max | **{cmix['max_rps_roofline']:.1f} rps** |")
    w("")
    w("**This is what sizes the load suite.** A staircase run steps to 100% of")
    w("this figure in 5% increments, so every level is expressed as a fraction of")
    w("theoretical capacity rather than an arbitrary rps number that means nothing")
    w("on different hardware.\n")

    w("### Per-category cost\n")
    w("| category | share | in tok | out tok | TFLOP | bound |")
    w("|---|---|---|---|---|---|")
    import math
    for cat in CATEGORIES:
        i = int(math.exp(cat.in_mu + cat.in_sigma ** 2 / 2))
        o = int(math.exp(cat.out_mu + cat.out_sigma ** 2 / 2))
        cc = capacity(m, hw, i, o, batch=146)
        w(f"| {cat.name} | {cat.weight:.0%} | {i} | {o} | "
          f"{cc['per_request_tflops']:.2f} | {cc['bound_by'].split('/')[0]} |")
    w("")
    w("The spread is the point. `summarize` is ~20x the FLOPs of `chat`, and")
    w("`creative` is decode-heavy where `summarize` is prefill-heavy. A suite that")
    w("used one average request would hide both.\n")

    w("## Phase 2 projection: 235B on 8xH100\n")
    w(f"`{QWEN3_235B_A22B.name}`\n")
    w("| | |")
    w("|---|---|")
    w(f"| total parameters | {QWEN3_235B_A22B.total_params/1e9:.0f}B |")
    w(f"| active parameters | {QWEN3_235B_A22B.active_params/1e9:.1f}B |")
    w(f"| FLOPs per request | {big['per_request_tflops']:.1f} TFLOP |")
    w(f"| decode step reads | {big['decode_bytes_per_step_gb']:.0f} GB |")
    w(f"| bound by | {big['bound_by']} |")
    w(f"| roofline max | **{big['max_rps_roofline']:.1f} rps** |")
    w("")
    w("**Unvalidated.** The 1xH100 model was checked against measurement; this one")
    w("has not been. Treat it as a planning estimate only, and re-derive the suite")
    w("rates from a real `saturate` run before trusting any 8-GPU comparison.\n")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(L))
    print(f"wrote {OUT} ({len(L)} lines)")
    print(f"\n1xH100  roofline {c['max_rps_roofline']:.1f} rps vs measured "
          f"{MEASURED_MAX_RPS} = {MEASURED_MAX_RPS/c['max_rps_roofline']:.0%}")
    print(f"human mix roofline {cmix['max_rps_roofline']:.1f} rps "
          f"({mix_in} in / {mix_out} out)")
    print(f"8xH100 235B roofline {big['max_rps_roofline']:.1f} rps (unvalidated)")


if __name__ == "__main__":
    main()
